
backend:
  name: github
  repo: vineetl007/math-lms
  branch: main
  auth_type: device

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "videos"
    label: "Videos"
    folder: "content/videos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "YouTube URL", name: "youtube", widget: "string" }
